name: book_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'  # Make sure it's above 2.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Updated for null safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
