name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up Flutter SDK manually
      - name: Set up Flutter SDK
        run: |
          sudo apt update
          sudo apt install -y unzip curl
          curl -LO https://storage.googleapis.com/download.flutter.io/flutter_linux_3.19.0-stable.tar.xz
          tar xf flutter_linux_3.19.0-stable.tar.xz
          sudo mv flutter /usr/local/bin/flutter
          flutter doctor

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Artifact upload (Optional) - You can comment it out if you don't need to upload the APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
